# Generated by Django 6.0 on 2026-05-13 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobiles', '0002_wishlist_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_mobile_1', to='mobiles.mobilevariant')),
                ('mobile_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_mobile_2', to='mobiles.mobilevariant')),
                ('mobile_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_mobile_3', to='mobiles.mobilevariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('mobile_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobilevariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'mobile_variant')},
            },
        ),
    ]
