# Generated by Django 6.0 on 2026-05-06 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_capacity', models.IntegerField(blank=True, null=True)),
                ('screen_size', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('screen_type', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('brand', 'model_name', 'model_number')},
            },
        ),
        migrations.CreateModel(
            name='MobileVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('ram', models.IntegerField(help_text='RAM in MB')),
                ('storage', models.IntegerField(help_text='Storage in MB')),
                ('primary_camera', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_camera', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mobiles.mobile')),
            ],
            options={
                'unique_together': {('mobile', 'color', 'ram', 'storage')},
            },
        ),
        migrations.CreateModel(
            name='MobilePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('product_title', models.TextField(blank=True, null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('list_price', models.IntegerField(blank=True, null=True)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('customer_rating', models.FloatField(blank=True, null=True)),
                ('availability', models.CharField(default='in stock', max_length=20)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='mobiles.mobilevariant')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mobile')},
            },
        ),
    ]
